Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "master"
  config.vm.network "private_network", ip: "10.0.0.5", netmask: "255.255.255.0", auto_config: true
  config.vm.provision "shell", path: "./startup.sh"
  config.vm.synced_folder "./master", "/home/vagrant/Terrible"
end