---
- hosts: dbs
  become: true
  tasks:
    - name: Downloading neccessities
      apt:
        pkg:
          - dirmngr
          - gnupg
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: latest
        update_cache: true
    - name: Downloading repo
      shell: "wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -"     
    - name: Adding repo
      shell: "sudo add-apt-repository 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse'"
    - name: Downloading MongoDB
      apt:
        name=mongodb-org
        state=present
    - name: Changing config file
      shell: "sudo sed -i 's/127.0.0.1/10.0.2.6/g' /etc/mongod.conf"
    - name: Start MongoDB
      systemd:
        state: started
        name: mongod