Vagrant.configure("2") do |config|

  # => Slave Box 1
  config.vm.define "webapp" do |webapp|
    webapp.vm.box = "generic/ubuntu2010"
    webapp.vm.hostname = "webapp"
    webapp.vm.network "private_network", ip: "10.0.0.5", netmask: "255.255.255.0", auto_config: true
    webapp.vm.provision "shell", inline: "sudo apt install -y ansible python3-pip"
  end

  # => Slave Box 2
  config.vm.define "db" do |db|
    db.vm.box = "generic/ubuntu2010"
    db.vm.hostname = "mongodb"
    db.vm.network "private_network", ip: "10.0.0.6", netmask: "255.255.255.0", auto_config: true
    db.vm.provision "shell", inline: "sudo apt install -y ansible"
  end

  # => Master Box
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2010"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.0.0.2", netmask: "255.255.255.0", auto_config: true
    master.vm.provision "shell", inline: "sudo apt install -y ansible"
    master.vm.provision "file", source: "./hosts", destination: "/tmp/hosts"
    master.vm.provision "shell", inline: "sudo mv /tmp/hosts /etc/ansible/hosts"
    master.vm.provision "file", source: "./mongod.conf", destination: "/home/vagrant/mongod.conf"
    master.vm.provision "file", source: "./app.py", destination: "/home/vagrant/app.py"
    master.vm.provision "file", source: "./playbook_dbs.yml", destination: "/home/vagrant/ansible/playbook_dbs.yml"
    master.vm.provision "file", source: "./playbook_webapps.yml", destination: "/home/vagrant/ansible/playbook_webapps.yml"
    # master.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible/playbook_dbs.yml -u vagrant"
    # master.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible/playbook_webapps.yml -u vagrant"  
  end

end
